twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@project_template/_includes/form/custom_types.html.twig'
    paths:
        '%kernel.project_dir%/templates/': project_template

when@test:
    twig:
        strict_variables: true
