services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    command: php -S 0.0.0.0:8000 -t public

  database:
    image: mysql:8.4.5
    container_name: ${PROJECT_NAME}-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: company_score_db
      MYSQL_USER: company_score
      MYSQL_PASSWORD: password
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database_data:
